# Generated by Django 4.1.5 on 2023-01-30 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("wait", "Wait"),
                            ("game", "Game"),
                            ("completed", "Completed"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "game_session",
            },
        ),
        migrations.CreateModel(
            name="UserScores",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="user_scores",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("scores", models.IntegerField()),
            ],
            options={
                "db_table": "user_scores",
            },
        ),
        migrations.CreateModel(
            name="UserGameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("not_ready", "Not Ready"),
                            ("ready", "Ready"),
                            ("playing", "Playing"),
                            ("done", "Done"),
                            ("disconnected", "Disconnected"),
                        ]
                    ),
                ),
                (
                    "color",
                    models.TextField(
                        choices=[("white", "White"), ("black", "Black"), ("red", "Red")]
                    ),
                ),
                ("is_winner", models.BooleanField()),
                ("scores", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_game_sessions",
                        to="app.gamesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_game_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_game_session",
            },
        ),
        migrations.CreateModel(
            name="PieceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("king", "King"),
                            ("queen", "Queen"),
                            ("rook", "Rook"),
                            ("bishop", "Bishop"),
                            ("knight", "Knight"),
                            ("pawn", "Pawn"),
                        ]
                    ),
                ),
                (
                    "color",
                    models.TextField(
                        choices=[("white", "White"), ("black", "Black"), ("red", "Red")]
                    ),
                ),
                ("position", models.CharField(max_length=4)),
                (
                    "game_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.gamesession",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="users",
            field=models.ManyToManyField(
                related_name="game_sessions",
                through="app.UserGameSession",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
